 const groupedSubEvents = {
    Hinduism: {
      "Pre-Wedding": [
        "Engagement Ceremony (Sagai)",
        "Mehendi Ceremony",
        "Sangeet Ceremony",
        "Tilak Ceremony",
        "Haldi Ceremony",
        "Roka Ceremony",
      ],
      "Main Ceremony": [
        "Wedding Day Ceremonies",
        "Kanyadaan",
        "Mangal Pheras",
        "Saat Pheras",
        "Sindoor Daan",
        "Mangal Sutra",
      ],
      "Post-Wedding": [
        "Vidaai",
        "Reception",
        "Blessing Ceremony (Aashirvaad)",
        "Dwar Rokai and Griha Pravesh",
        "Mooh Dikhai and Pag Phera",
        "Griha Pravesh",
      ],
      "Bride's Rituals": ["Kaleera Ceremony", "Chooda Ceremony"],
    },
  };

   const weddingEvents = [
    { name: "Hindu Wedding", religion: "Hinduism" },
    { name: "Christian Wedding", religion: "Christianity" },
    { name: "Muslim Wedding", religion: "Islam" },
    { name: "Sikh Wedding", religion: "Sikhism" },
    { name: "Buddhist Wedding", religion: "Buddhism" },
    { name: "Jain Wedding", religion: "Jainism" },
  ];
  
  const subEvents = {
    Hinduism: [
      "Engagement Ceremony (Sagai)",
      "Mehendi Ceremony",
      "Sangeet Ceremony",
      "Tilak Ceremony",
      "Haldi Ceremony",
      "Roka Ceremony",
      "Wedding Day Ceremonies",
      "Vidaai",
      "Reception",
      "Blessing Ceremony (Aashirvaad)",
      "Dwar Rokai and Griha Pravesh",
      "Mooh Dikhai and Pag Phera",
      "Kaleera Ceremony",
      "Chooda Ceremony",
      "Kanyadaan",
      "Mangal Pheras",
      "Saat Pheras",
      "Sindoor Daan",
      "Mangal Sutra",
      "Griha Pravesh",
    ],
    Christianity: [
      "Processional",
      "Presentation",
      "Moment of Silence",
      "Homily",
      "Prayer",
      "Exchanging of Vows",
      "Unity Ceremony",
      "Exchanging of Rings",
      "Pronouncement",
      "Recessional",
      "Reception",
    ],
    Islam: [
      "Salat al-Istikhara – Prayers to Allah",
      "Imam Zamin – Groom's mother to bless the bride",
      "Mangni – The ring ceremony",
      "Manjha – Haldi Ceremony",
      "Heena aka Mehndi time",
      "Sanchaq – Groom's family visit",
      "Baraat arrival – Here comes the King",
      "Nikah – The Main Ceremony",
      "Fatiha – First verse of holy Quran",
      "Mehar – A contract for life",
      "Arsi Mushraf – See through Mirror",
      "Rukhsat – The Goodbyes",
    ],
    Sikhism: ["Anand Karaj", "Reception"],
    Buddhism: [
      "Decorations",
      "The Couple's Outfits",
      "The Event Coordinator",
      "Meditations and Readings",
      "Vows",
      "Offerings to the Buddha",
      "Blessings by Monks",
    ],
    Jainism: ["Lagna Lekhan", "Mangal Pheras"],
  };


  export { weddingEvents, subEvents, groupedSubEvents };